version: '3.1'

services:
  database:
    image: mysql:8.3.0-oracle
    container_name: storage
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  elastichsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    network_mode: "host"

volumes:
    db:
